export type SectionContent = {
  title: string;
  paragraphs?: string[];
  bullets?: string[];
};

export type SitePath = '/' | '/privacy/' | '/terms/' | '/support/' | '/data-deletion/';

export const siteConfig = {
  appName: 'SnapFresh',
  legalName: 'SnapFresh',
  contactEmail: 'support@ujascode.co.uk',
  supportWindow: 'We aim to reply within three business days.',
  effectiveDate: 'March 10, 2026',
  lastUpdated: 'March 10, 2026'
};

export function toPageHref(currentPath: SitePath, targetPath: SitePath): string {
  if (currentPath === '/') {
    return targetPath === '/' ? './' : targetPath.slice(1);
  }

  return targetPath === '/' ? '../' : `../${targetPath.slice(1)}`;
}

export function toAssetHref(currentPath: SitePath, assetName: string): string {
  return currentPath === '/' ? `./${assetName}` : `../${assetName}`;
}

export const supportedLanguages = [
  'English',
  'Punjabi',
  'Chinese',
  'Hindi',
  'Spanish',
  'French',
  'German',
  'Russian',
  'Portuguese',
  'Italian',
  'Romanian',
  'Azerbaijani',
  'Dutch'
];

export const homeHighlights = [
  {
    title: 'Photo-first meal analysis',
    body:
      'SnapFresh uses your camera or photo library to identify what is on the plate, estimate nutrition, and generate a simple quality score.'
  },
  {
    title: 'History, goals, and hydration',
    body:
      'Scan history, nutrition goals, and optional water logs help you spot patterns instead of judging one meal at a time.'
  },
  {
    title: 'Built for international users',
    body: `SnapFresh currently supports ${supportedLanguages.length} interface languages, along with settings for theme, language, and premium layouts.`
  }
];

export const trustSignals = [
  'Email and Google sign-in are handled through Clerk.',
  'Basic profile records are synced to Supabase when a signed-in user enters the app.',
  'Meal photos and notes are sent to an analysis service to generate AI-based food insights.',
  'Scan history, profile goals, water logs, language, and theme settings are also stored locally on the device.',
  'AI results are presented as estimates and are not medical advice.'
];

export const privacySections: SectionContent[] = [
  {
    title: '1. Scope',
    paragraphs: [
      'This Privacy Policy explains how SnapFresh collects, uses, stores, and shares information when you use the SnapFresh mobile app, the SnapFresh website, and related support pages.',
      'It reflects the current SnapFresh experience, including account sign-in, meal photo analysis, scan history, hydration tracking, nutrition preferences, and related support and account management features.'
    ]
  },
  {
    title: '2. Information We Collect',
    bullets: [
      'Account information such as your email address, name, profile image, sign-in provider, and account identifiers when you create an account or sign in.',
      'Meal analysis inputs such as photos you capture with the camera or choose from your photo library, optional notes or descriptions you provide, and the resulting detected items, scores, captions, and nutrition estimates generated by the service.',
      'Profile and goal information such as height, weight, date of birth, gender, calorie goals, macro goals, and related nutrition preference data, if you choose to provide it.',
      'Hydration and tracking information such as water logs, meal history, favorites, and other entries you create while using the app.',
      'Device, app, and usage information such as screen views, feature interactions, app settings, language, theme, subscription status indicators, diagnostics, and other technical data used to operate, secure, and improve the service.',
      'Support communications and account requests you send us, including the email address and message content you use when contacting support or requesting data access or deletion.'
    ]
  },
  {
    title: '3. Permissions and Device Access',
    bullets: [
      'Camera access is requested so you can capture meal photos for analysis.',
      'Photo library access is requested so you can upload existing food photos for analysis.',
      'Microphone or speech recognition access may be requested if you use voice input features to describe meals.',
      'Secure local storage may be used for authentication tokens, app preferences, and related session data needed to keep you signed in and provide app functionality.',
      'You can control these permissions in your device settings, but certain features will not work properly if access is disabled.'
    ]
  },
  {
    title: '4. How We Use Information',
    bullets: [
      'To create and maintain user accounts and authenticate users securely.',
      'To process meal photos, notes, and related inputs using automated systems and AI-assisted analysis in order to identify food items and generate estimated nutrition and meal quality insights.',
      'To store and display scan history, hydration logs, favorites, and personalized goal settings.',
      'To provide, maintain, troubleshoot, secure, and improve the app, website, and related services.',
      'To respond to support requests, investigate misuse, enforce our terms, and comply with legal obligations.',
      'To offer, manage, and support premium or paid features, where available.'
    ]
  },
  {
    title: '5. Service Providers and Infrastructure',
    paragraphs: [
      'SnapFresh uses trusted third-party service providers to operate core parts of the service. For example, Clerk may be used for account authentication, Supabase may be used for application databases and storage, PostHog may be used for product analytics, and AI service providers may be used to process meal images and related inputs in order to return structured food insights and nutrition estimates.',
      'When you submit a meal for analysis, the photo and related input you provide may be transmitted securely to backend systems and service providers involved in generating the analysis result. We require service providers to support our operations only for authorized purposes and subject to appropriate safeguards.'
    ]
  },
  {
    title: '6. Local and Cloud Storage',
    bullets: [
      'Information stored on your device may include app preferences, cached scan history, hydration data, goals, theme, language settings, and certain session-related data.',
      'Account-linked information stored in cloud systems may include profile data, meal analysis records, hydration records, settings, support records, and operational data needed to provide the service.',
      'We retain information for as long as reasonably necessary to provide the service, maintain security, comply with legal obligations, resolve disputes, and enforce our agreements.',
      'When you request deletion of your account-linked data, we will delete or de-identify applicable information within a reasonable period, except where retention is required for legal, security, fraud-prevention, or legitimate operational reasons.'
    ]
  },
  {
    title: '7. Sharing',
    paragraphs: [
      'We do not sell your personal information. We may share information with vendors and service providers that help us operate authentication, hosting, storage, analytics, support, subscriptions, security, and meal analysis features.',
      'We may also disclose information where necessary to comply with law, respond to lawful requests, enforce our terms, detect or prevent fraud or abuse, or protect the rights, safety, and security of our users, the public, or SnapFresh.'
    ]
  },
  {
    title: '8. Your Choices and Rights',
    bullets: [
      'You can choose not to provide optional profile, goal, hydration, or meal note information.',
      'You can manage camera, photo library, and microphone permissions through your device settings.',
      'You can request deletion of your account-linked data by using the process described on the data deletion page or by contacting us directly.',
      'Deleting the app from your device may remove locally stored app data from that device, but it does not automatically delete account-linked information stored in our cloud systems.',
      'Depending on where you live, you may have rights to request access to, correction of, deletion of, or portability of your personal information, or to object to or restrict certain processing. You can contact us to make such a request.'
    ]
  },
  {
    title: '9. Nutrition Information Disclaimer',
    paragraphs: [
      'SnapFresh provides estimated food recognition, nutrition information, and meal quality insights for general informational purposes only.',
      'SnapFresh is not a medical service and does not provide medical, dietary, or professional healthcare advice. You should not rely on the app as a substitute for professional medical or nutritional guidance.'
    ]
  },
  {
    title: '10. Children',
    paragraphs: [
      'SnapFresh is not intended for children under 13, and we do not knowingly collect personal information from children under 13. If you believe a child under 13 has provided personal information to us, please contact us so we can review and take appropriate action.'
    ]
  },
  {
    title: '11. Changes and Contact',
    paragraphs: [
      'We may update this Privacy Policy from time to time. If we make material changes, we will update the Last Updated date on this page and, where appropriate, provide additional notice.',
      `For privacy questions or requests, contact us at ${siteConfig.contactEmail}.`
    ]
  }
];

export const termsSections: SectionContent[] = [
  {
    title: '1. Acceptance of Terms',
    paragraphs: [
      'By accessing or using SnapFresh, you agree to these Terms of Use. If you do not agree, you must not use the app or related services.',
      'These Terms apply to your use of the SnapFresh mobile application, website, and any related features or services we provide.'
    ]
  },
  {
    title: '2. What SnapFresh Provides',
    paragraphs: [
      'SnapFresh is a nutrition and meal insight application that allows users to create accounts, scan or upload meal images, receive AI-generated food recognition and nutrition estimates, track hydration, and manage personal goals and preferences.',
      'SnapFresh may update, modify, or discontinue features at any time as part of ongoing product improvements.'
    ]
  },
  {
    title: '3. AI and Health Disclaimer',
    bullets: [
      'Meal analysis results are generated using automated systems and AI and should be treated as estimates only.',
      'Nutrition values, calorie counts, macros, and meal quality scores may be incomplete, inaccurate, or unsuitable for your individual circumstances.',
      'SnapFresh is not a medical device and does not provide medical, dietary, or healthcare advice.',
      'You should not rely on SnapFresh for medical decisions, diagnosis, or treatment, and should consult a qualified healthcare professional for such matters.'
    ]
  },
  {
    title: '4. User Content',
    bullets: [
      'You may upload or submit content such as meal photos, notes, and other inputs ("User Content").',
      'You retain ownership of your User Content, but you grant SnapFresh a limited, non-exclusive, worldwide license to use, process, store, and display that content solely for the purpose of operating and improving the service.',
      'You are responsible for ensuring that you have the necessary rights to upload and use any content you submit.',
      'We may remove or restrict content that violates these Terms or applicable laws.'
    ]
  },
  {
    title: '5. Accounts and Security',
    bullets: [
      'You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account.',
      'You must provide accurate information when creating an account and keep it reasonably up to date.',
      'We may suspend, restrict, or terminate your account if we believe it is being used unlawfully, fraudulently, or in violation of these Terms.'
    ]
  },
  {
    title: '6. Acceptable Use',
    bullets: [
      'You agree not to misuse the service or attempt to disrupt, damage, or gain unauthorized access to SnapFresh systems or data.',
      'You must not reverse engineer, scrape, or extract data from the service except as permitted by law.',
      'You must not upload unlawful, harmful, or infringing content.',
      'You must not use SnapFresh for emergency or time-sensitive medical or health-related decisions.'
    ]
  },
  {
    title: '7. Premium Features and Billing',
    paragraphs: [
      'Some features of SnapFresh may require a paid subscription or in-app purchase. Where applicable, pricing and billing terms will be presented at the time of purchase.',
      'Subscriptions purchased through Apple are billed and managed by Apple and may automatically renew unless cancelled through your Apple account settings.',
      'You are responsible for managing your subscription and cancellation through the relevant platform.'
    ]
  },
  {
    title: '8. Intellectual Property',
    paragraphs: [
      'SnapFresh, including its software, design, branding, content, and underlying technology, is owned by SnapFresh or its licensors and is protected by intellectual property laws.',
      'You are granted a limited, non-transferable, non-exclusive license to use the app for personal, non-commercial purposes in accordance with these Terms.'
    ]
  },
  {
    title: '9. Disclaimer of Warranties',
    paragraphs: [
      'SnapFresh is provided on an "as is" and "as available" basis. To the maximum extent permitted by law, we disclaim all warranties, whether express or implied, including warranties of accuracy, reliability, fitness for a particular purpose, and uninterrupted availability.',
      'We do not guarantee that the service will be error-free, secure, or continuously available.'
    ]
  },
  {
    title: '10. Limitation of Liability',
    paragraphs: [
      'To the maximum extent permitted by law, SnapFresh will not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any loss of data, profits, or use arising from your use of the service.',
      'SnapFresh is not responsible for decisions you make based on meal analysis results, nutrition estimates, or other outputs provided by the app.'
    ]
  },
  {
    title: '11. Termination',
    paragraphs: [
      'We may suspend or terminate your access to SnapFresh at any time if you violate these Terms or if we reasonably believe your use of the service poses a risk to us, other users, or the platform.',
      'You may stop using the service at any time. Account deletion can be requested through the app or via the contact details provided.'
    ]
  },
  {
    title: '12. Changes and Contact',
    paragraphs: [
      'We may update these Terms from time to time. If we make material changes, we will update the effective date and, where appropriate, provide notice within the app or on our website.',
      'By continuing to use SnapFresh after changes take effect, you agree to the updated Terms.',
      `For questions about these Terms, contact us at ${siteConfig.contactEmail}.`
    ]
  }
];

export const supportTopics = [
  {
    title: 'Getting started',
    body:
      'SnapFresh lets you scan meals using your camera, upload photos, or describe food to receive AI-generated nutrition insights. Start by taking your first scan from the home screen and tapping "Analyze".'
  },
  {
    title: 'Sign-in and account access',
    body:
      'SnapFresh supports email and Google sign-in. If you cannot sign in, check that you are using the correct method. If the issue continues, contact support and include the email address linked to your account and any error message you saw.'
  },
  {
    title: 'Meal scans and AI estimates',
    body:
      'If a meal scan looks incorrect, let us know what the meal was and what the image showed. You can also add notes such as "grilled not fried" to improve results. AI-based analysis may not always be accurate, and your feedback helps improve the system.'
  },
  {
    title: 'Profile, dashboard, and water logs',
    body:
      'Your goals, hydration logs, and some settings may be stored locally on your device. If data appears missing, tell us whether this happened after reinstalling the app, updating it, or switching devices.'
  },
  {
    title: 'Premium features and subscriptions',
    body:
      'Some features are available through premium access. If you have issues with billing, upgrades, or locked features, ensure your subscription is active in your Apple account. For billing issues, Apple manages payments directly.'
  },
  {
    title: 'Troubleshooting issues',
    body:
      'If something is not working as expected, try restarting the app and ensuring you are on the latest version. When contacting support, include details such as your device type, app version, and steps to reproduce the issue.'
  },
  {
    title: 'Account deletion and data requests',
    body:
      'You can request deletion of your account and associated data at any time. Visit the data deletion page or contact support using the email below. Once processed, your data will be removed within a reasonable timeframe.'
  },
  {
    title: 'Contact support',
    body:
      'If you need help, contact us at support@snapfresh.app. Please include as much detail as possible, such as screenshots, device type, and steps to reproduce the issue. We typically respond within 24–48 hours.'
  }
];

export const deletionSections: SectionContent[] = [
  {
    title: 'What can be deleted',
    bullets: [
      'Your SnapFresh account and associated profile information.',
      'Meal scans, uploaded images, detected items, nutrition insights, and scan history linked to your account.',
      'Hydration logs, goals, preferences, and related app settings stored in your account.',
      'Support communications where they are no longer required for legal, security, or operational purposes.',
      'Locally stored app data such as cached history and settings when removed from your device or cleared through app controls.'
    ]
  },
  {
    title: 'How to delete your account',
    bullets: [
      'You can delete your account instantly from within the app by going to Settings and selecting "Delete Account".',
      `If you are unable to access the app, you can request deletion by emailing ${siteConfig.contactEmail} from the address associated with your account.`,
      'Include enough information for us to identify your account, such as your sign-in email address.'
    ]
  },
  {
    title: 'What happens next',
    bullets: [
      'If you use the in-app Delete Account option, your account and associated data are deleted immediately.',
      'For email requests, we may need to verify your identity before processing the request.',
      siteConfig.supportWindow,
      'We aim to complete email-based deletion requests within 30 days unless a longer period is required for legal, security, or fraud-prevention reasons.'
    ]
  },
  {
    title: 'Important notes',
    bullets: [
      'Account deletion is permanent and cannot be undone.',
      'Some limited data may be retained where required for legal compliance, security, or fraud prevention.',
      'Deleting your account removes cloud-linked data. To remove any remaining data stored only on your device, uninstall the app or clear local data using available app controls.'
    ]
  }
];
